try:
  print(x)
except NameError:
  print("Variable x is not defined")
except:
  print("Something else went wrong") 
  
  #example2
  
  try:
  print("Hello")
except:
  print("Something went wrong")
else:
  print("Nothing went wrong") 
  
  #example3
  
  try:
  print(x)
except:
  print("Something went wrong")
finally:
  print("The 'try except' is finished") 
